kind: ConfigMap
apiVersion: v1
metadata:
  name: cntlm-config-map
data:
  cntlm.conf: |-
    #
    # Cntlm Authentication Proxy Configuration
    #
    # NOTE: all values are parsed literally, do NOT escape spaces,
    # do not quote. Use 0600 perms if you use plaintext password.
    #
    Username        {{ .Values.conf.username }}
    Domain          {{ .Values.conf.domain }}
    {{- if .Values.conf.password }}
    Password        {{ .Values.conf.password }}
    {{- end }}   
    
    # NOTE: Use plaintext password only at your own risk
    # Use hashes instead. You can use a "cntlm -M" and "cntlm -H"
    # command sequence to get the right config for your environment.
    # See cntlm man page
    # Example secure config shown below.
    # PassLM          1AD35398BE6565DDB5C4EF70C0593492
    # PassNT          77B9081511704EE852F94227CF48A793
    ### Only for user 'testuser', domain 'corp-uk'
    # PassNTLMv2      D5826E9C665C37C80B53397D5C07BBCB
    {{- if .Values.conf.passlm }}
    PassLM          {{ .Values.conf.passlm }}
    {{- end }}   
    {{- if .Values.conf.passnt }}
    PassNT          {{ .Values.conf.passnt }}
    {{- end }}   
    {{- if .Values.conf.passntlmv2 }}
    PassNTLMv2      {{ .Values.conf.passntlmv2 }}
    {{- end }}   
    
    # Specify the netbios hostname cntlm will send to the parent
    # proxies. Normally the value is auto-guessed.
    #
    # Workstation   netbios_hostname
    {{- if .Values.conf.workstation }}
    Workstation          {{ .Values.conf.workstation }}
    {{- end }}
    
    # List of parent proxies to use. More proxies can be defined
    # one per line in format <proxy_ip>:<proxy_port>
    #
    {{- range .Values.conf.proxies }}
    Proxy {{ . }}
    {{- end }}   
    
    # List addresses you do not want to pass to parent proxies
    # * and ? wildcards can be used
    #
    NoProxy         {{ join ", " .Values.conf.noproxies }}
    
    # Cntlm listens on 127.0.0.1:3128 by default
    #
    {{- range .Values.conf.interfaces }}
    Listen {{ . }}
    {{- end }}   
    
    # If you wish to use the SOCKS5 proxy feature as well, uncomment
    # the following option. It can be used several times
    # to have SOCKS5 on more than one port or on different network
    # interfaces (specify explicit source address for that).
    #
    # WARNING: The service accepts all requests, unless you use
    # SOCKS5User and make authentication mandatory. SOCKS5User
    # can be used repeatedly for a whole bunch of individual accounts.
    #
    #SOCKS5Proxy    8010
    #SOCKS5User     dave:password
    {{- if .Values.conf.socks5.proxy }}
    SOCKS5Proxy          {{ .Values.conf.socks5.proxy }}
    {{- end }}
    {{- if .Values.conf.socks5.user }}
    SOCKS5User          {{ .Values.conf.socks5.user }}
    {{- end }}
    
    # Use -M first to detect the best NTLM settings for your proxy.
    # Default is to use the only secure hash, NTLMv2, but it is not
    # as available as the older stuff.
    #
    # This example is the most universal setup known to man, but it
    # uses the weakest hash ever. I won't have it's usage on my
    # conscience. :) Really, try -M first.
    #
    #Auth           LM
    #Flags          0x06820000
    {{- if .Values.conf.auth }}
    Auth          {{ .Values.conf.auth }}
    {{- end }}
    {{- if .Values.conf.flags }}
    Flags          {{ .Values.conf.flags }}
    {{- end }}
    
    # Enable to allow access from other computers
    #
    Gateway {{ .Values.conf.gateway }}
    
    # Useful in Gateway mode to allow/restrict certain IPs
    # Specifiy individual IPs or subnets one rule per line.
    #
    #Allow		127.0.0.1
    #Deny		0/0
    {{- range .Values.conf.allowed }}
    Allow {{ . }}
    {{- end }}   
    {{- range .Values.conf.denied }}
    Deny {{ . }}
    {{- end }}   
    
    # GFI WebMonitor-handling plugin parameters, disabled by default
    #
    #ISAScannerSize     1024
    #ISAScannerAgent    Wget/
    #ISAScannerAgent    APT-HTTP/
    #ISAScannerAgent    Yum/

    {{- if .Values.conf.isa.size }}
    ISAScannerSize          {{ .Values.conf.isa.size }}
    {{- end }}
    {{- range .Values.conf.isa.agent }}
    ISAScannerAgent {{ . }}
    {{- end }}   
    
    # Headers which should be replaced if present in the request
    #
    #Header		User-Agent: Mozilla/4.0 (compatible; MSIE 5.5; Windows 98)
    {{- range .Values.conf.headers }}
    Header {{ . }}
    {{- end }}   
    
    # Tunnels mapping local port to a machine behind the proxy.
    # The format is <local_port>:<remote_host>:<remote_port>
    #
    #Tunnel		11443:remote.com:443
    {{- if .Values.conf.tunnel }}
    Tunnel          {{ .Values.conf.tunnel }}
    {{- end }}

    # Enable SSPI for Windows clients.
    # Only NTLM is supported for now.
    #
    #SSPI	NTLM
    {{- if .Values.conf.sspi }}
    SSPI	NTLM
    {{- end }}
